import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Button, useTheme } from '@mui/material';

import AnimatedPage from './_animatedPage';
import PresContainer from '../src/components/templates/PresContainer';
import ContentColumn from '../src/components/molecules/ContentColumn';
import ImageColumn from '../src/components/molecules/ImageColumn';
import Link from 'next/link';
import CallToAction from '../src/components/atoms/CallToAction';

const Home: NextPage = () => {
  const theme = useTheme();

  return (
    <AnimatedPage>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div
        className='page__layout'
        style={{
          height: '50vh',
          width: '100%',
          display: 'flex',
          // marginTop: NavHeight,
        }}>
        <div
          className='content'
          style={{
            backgroundImage:
              'radial-gradient(rgba(0,0,0, 0.3), rgba(0,0,0,0)), url(/profil-2-min.webp)',
            backgroundPosition: 'bottom left',
            backgroundSize: 'cover',
            height: '100%',
            flex: 1,
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            color: 'white',
          }}>
          <div
            className='content__container'
            style={{
              textAlign: 'center',
            }}>
            <h1
              style={{
                fontSize: '4rem',
                margin: 0,
              }}>
              <span
                style={{
                  color: theme.palette.primary.main,
                }}>
                W
              </span>
              ing Foil
            </h1>
            <h2
              style={{
                margin: 0,
                fontWeight: 500,
              }}>
              Cassis | La Ciotat
            </h2>
          </div>
        </div>
      </div>

      <main>
        <PresContainer>
          <ContentColumn header={"Qu'est ce que le Wing Foil ?"}>
            <p>
              La Wing est une aile légère et maniable qui vous tracte et vous
              permet de décoller au-dessus de la surface de l’eau, grâce au foil
              fixé sous la planche.
            </p>
            <p>
              Vous retrouverez les sensations du kitesurf, du surf et de la
              planche à voile. Un mix de tous les sports de glisse mais avec un
              apprentissage plus rapide et ludique.
            </p>
            <p>
              La Wing procure des sensations uniques et un sentiment de liberté.
            </p>
          </ContentColumn>
          <ImageColumn imagePath={'/sylvain-min-gimp.webp'} />
        </PresContainer>

        <PresContainer>
          <ContentColumn header={'Par où commencer ?'}>
            <p>L’initiation se déroule en trois étapes :</p>
            <ul
              style={{
                listStyleType: 'square',
              }}>
              <li>Maniement de l’aile à terre.</li>
              <li>
                Navigation sur une planche de paddle ou planche à voile sans
                foil.
              </li>
              <li>
                Navigation avec la planche de Wingfoil et premiers décollages !
              </li>
            </ul>
            <p>
              Une session de foil tracté par un bateau pourra être proposé aux
              initiations d’une heure et les jours sans vent.
            </p>

            <p style={{ fontWeight: 'bold' }}>
              * Matériel adapté à tous les niveaux et tous les gabarits
            </p>

            <CallToAction label='découvrir' />
          </ContentColumn>
          <ImageColumn imagePath={'/foil-1-min-gimp.webp'} />
        </PresContainer>
      </main>
    </AnimatedPage>
  );
};

export default Home;
