import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>TO DO</h1>
      <ul>
        <li>Cypress</li>
        <li>Jest</li>
        <li>Storybook</li>
        <li>------</li>
        <li>Material Ui</li>
        <li>Framer motion</li>
        <li>styled components ?</li>
        <li>Page transition</li>
      </ul>
    </div>
  );
};

export default Home;
