import { Container } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import AnimatedPage from './_animatedPage';

const Home: NextPage = () => {
  return (
    <AnimatedPage>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container maxWidth='xl' style={{}}>
        <h1>TO DO</h1>
        <ul>
          <li>Cypress</li>
          <li>Jest</li>
          <li>Storybook</li>
          <li>------</li>
          <li>
            <s>Material Ui</s>
          </li>
          <li>
            <s>Framer motion</s>
          </li>
          <li>styled components ?</li>
          <li>
            <s>Page transition</s>
          </li>
        </ul>
      </Container>
    </AnimatedPage>
  );
};

export default Home;
